// ============================================================
//  ALL PORSCHE MODELS — Complete lineup with all variants
// ============================================================
const models = [

    // ─────────────── 911 FAMILY ─────────────────────────────
    {
        id: "911-carrera",
        family: "911",
        name: "911 Carrera",
        tagline: "The benchmark. The legend.",
        description: "The original sports car icon with a rear-engine layout and flat-six engine that has defined the benchmark for six decades.",
        price: "$114,400",
        specs: { power: "379 hp", acceleration: "4.0 s", topSpeed: "182 mph", engine: "3.0L Flat-6" },
        badge: "Icon",
        badgeClass: "badge-icon",
        image: "assets/images/top_view/ezgif-frame-020.jpg",
        link: "model-details.html?model=911-carrera"
    },
    {
        id: "911-carrera-s",
        family: "911",
        name: "911 Carrera S",
        tagline: "More power. More presence.",
        description: "Twin-turbocharged flat-six with 450 hp delivers an exhilarating driving experience and Sport Chrono Package as standard.",
        price: "$133,300",
        specs: { power: "450 hp", acceleration: "3.5 s", topSpeed: "188 mph", engine: "3.0L Flat-6 Biturbo" },
        badge: "S",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-015.jpg",
        link: "model-details.html?model=911-carrera-s"
    },
    {
        id: "911-carrera-4s",
        family: "911",
        name: "911 Carrera 4S",
        tagline: "All-wheel confidence.",
        description: "The breadth of terrains you can conquer grows wider with Porsche's intelligent AWD system and 450 hp.",
        price: "$141,500",
        specs: { power: "450 hp", acceleration: "3.4 s", topSpeed: "188 mph", engine: "3.0L Flat-6 Biturbo" },
        badge: "AWD",
        badgeClass: "badge-new",
        image: "assets/images/top_view/ezgif-frame-028.jpg",
        link: "model-details.html?model=911-carrera-4s"
    },
    {
        id: "911-targa-4s",
        family: "911",
        name: "911 Targa 4S",
        tagline: "Open air. Pure performance.",
        description: "The iconic Targa bar and retractable glass rear window — open-air driving with all-season capability.",
        price: "$151,700",
        specs: { power: "450 hp", acceleration: "3.6 s", topSpeed: "188 mph", engine: "3.0L Flat-6 Biturbo" },
        badge: "Targa",
        badgeClass: "badge-icon",
        image: "assets/images/side_view/ezgif-frame-012.jpg",
        link: "model-details.html?model=911-targa-4s"
    },
    {
        id: "911-turbo-s",
        family: "911",
        name: "911 Turbo S",
        tagline: "The ultimate 911.",
        description: "640 hp. 2.6 seconds to 60. The most powerful 911 ever built for the road — no compromises, no apologies.",
        price: "$226,700",
        specs: { power: "640 hp", acceleration: "2.6 s", topSpeed: "205 mph", engine: "3.7L Flat-6 Biturbo" },
        badge: "Turbo S",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-035.jpg",
        link: "model-details.html?model=911-turbo-s"
    },
    {
        id: "911-gt3",
        family: "911",
        name: "911 GT3",
        tagline: "Race-bred. Road-legal.",
        description: "A naturally aspirated 4.0L flat-six revving to 9,000 rpm. A rear-axle steering system. Track DNA you can drive every day.",
        price: "$167,000",
        specs: { power: "502 hp", acceleration: "3.4 s", topSpeed: "199 mph", engine: "4.0L Flat-6 NA" },
        badge: "GT3",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-038.jpg",
        link: "model-details.html?model=911-gt3"
    },
    {
        id: "911-gt3-rs",
        family: "911",
        name: "911 GT3 RS",
        tagline: "Aerodynamics as a weapon.",
        description: "Active aerodynamics, 518 hp, and a downforce figure that defies road-car logic. The most track-focused 911 of all time.",
        price: "$223,800",
        specs: { power: "518 hp", acceleration: "3.2 s", topSpeed: "184 mph", engine: "4.0L Flat-6 NA" },
        badge: "GT3 RS",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-040.jpg",
        link: "model-details.html?model=911-gt3-rs"
    },
    {
        id: "911-dakar",
        family: "911",
        name: "911 Dakar",
        tagline: "Off-road soul. On-road heart.",
        description: "50mm higher. All-terrain tyres. Two lift modes. A 911 that can go literally anywhere — sand dunes included.",
        price: "$222,000",
        specs: { power: "473 hp", acceleration: "3.4 s", topSpeed: "149 mph", engine: "3.0L Flat-6 Biturbo" },
        badge: "Rally",
        badgeClass: "badge-new",
        image: "assets/images/top_view/ezgif-frame-008.jpg",
        link: "model-details.html?model=911-dakar"
    },

    // ─────────────── TAYCAN FAMILY ──────────────────────────
    {
        id: "taycan",
        family: "Taycan",
        name: "Taycan",
        tagline: "Soul. Electrified.",
        description: "The first all-electric Porsche sports car. 0-60 in 5.1 seconds with zero emissions and unmistakable Porsche character.",
        price: "$90,900",
        specs: { power: "402 hp", acceleration: "5.1 s", topSpeed: "143 mph", engine: "Dual Motor EV" },
        badge: "Electric",
        badgeClass: "badge-electric",
        image: "assets/images/side_view/ezgif-frame-005.jpg",
        link: "model-details.html?model=taycan"
    },
    {
        id: "taycan-4s",
        family: "Taycan",
        name: "Taycan 4S",
        tagline: "More performance. More range.",
        description: "All-wheel drive electric performance with 490 hp and a 93.4 kWh battery for exhilarating range.",
        price: "$112,120",
        specs: { power: "490 hp", acceleration: "3.8 s", topSpeed: "155 mph", engine: "Dual Motor EV AWD" },
        badge: "Electric",
        badgeClass: "badge-electric",
        image: "assets/images/side_view/ezgif-frame-015.jpg",
        link: "model-details.html?model=taycan-4s"
    },
    {
        id: "taycan-gts",
        family: "Taycan",
        name: "Taycan GTS",
        tagline: "Gran Turismo Sport. Electric.",
        description: "Sport Chrono Package standard. PASM sport suspension. The most emotionally focused Taycan variant available.",
        price: "$134,900",
        specs: { power: "590 hp", acceleration: "3.3 s", topSpeed: "155 mph", engine: "Dual Motor EV AWD" },
        badge: "GTS",
        badgeClass: "badge-sport",
        image: "assets/images/side_view/ezgif-frame-022.jpg",
        link: "model-details.html?model=taycan-gts"
    },
    {
        id: "taycan-turbo",
        family: "Taycan",
        name: "Taycan Turbo",
        tagline: "Electric power, redefined.",
        description: "675 hp, a 0-60 in 2.8 seconds and a 93.4 kWh battery. The Taycan Turbo S is the fastest-accelerating Porsche ever.",
        price: "$175,000",
        specs: { power: "675 hp", acceleration: "2.8 s", topSpeed: "162 mph", engine: "Dual Motor EV AWD" },
        badge: "Turbo",
        badgeClass: "badge-sport",
        image: "assets/images/side_view/ezgif-frame-030.jpg",
        link: "model-details.html?model=taycan-turbo"
    },
    {
        id: "taycan-cross-turismo",
        family: "Taycan",
        name: "Taycan Cross Turismo",
        tagline: "Electric adventure, elevated.",
        description: "The estate body with 30mm more ride height, a full-length panoramic roof and 1,200L of cargo space — sporty versatility.",
        price: "$96,300",
        specs: { power: "402 hp", acceleration: "5.1 s", topSpeed: "137 mph", engine: "Dual Motor EV AWD" },
        badge: "Cross",
        badgeClass: "badge-new",
        image: "assets/images/side_view/ezgif-frame-038.jpg",
        link: "model-details.html?model=taycan-cross-turismo"
    },
    {
        id: "taycan-sport-turismo",
        family: "Taycan",
        name: "Taycan Sport Turismo",
        tagline: "Sports car. Family car. One car.",
        description: "Estate practicality with Taycan performance — an additional rear seat, vast luggage space, and zero compromise on speed.",
        price: "$93,100",
        specs: { power: "402 hp", acceleration: "5.1 s", topSpeed: "143 mph", engine: "Dual Motor EV AWD" },
        badge: "Touring",
        badgeClass: "badge-icon",
        image: "assets/images/side_view/ezgif-frame-040.jpg",
        link: "model-details.html?model=taycan-sport-turismo"
    },

    // ─────────────── PANAMERA FAMILY ────────────────────────
    {
        id: "panamera",
        family: "Panamera",
        name: "Panamera",
        tagline: "The sports car for four.",
        description: "Performance and comfort in perfect harmony. A 4-door sports car that doesn't ask you to choose.",
        price: "$102,800",
        specs: { power: "348 hp", acceleration: "5.0 s", topSpeed: "169 mph", engine: "2.9L V6 Biturbo" },
        badge: "GT",
        badgeClass: "badge-icon",
        image: "assets/images/top_view/ezgif-frame-003.jpg",
        link: "model-details.html?model=panamera"
    },
    {
        id: "panamera-4s",
        family: "Panamera",
        name: "Panamera 4S",
        tagline: "Grand touring perfected.",
        description: "449 hp, all-wheel drive, and a Sport Chrono Package that proves a luxury saloon can still excite.",
        price: "$131,700",
        specs: { power: "449 hp", acceleration: "4.0 s", topSpeed: "182 mph", engine: "2.9L V6 Biturbo" },
        badge: "4S",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-010.jpg",
        link: "model-details.html?model=panamera-4s"
    },
    {
        id: "panamera-gts",
        family: "Panamera",
        name: "Panamera GTS",
        tagline: "Gran Turismo Sport. Four doors.",
        description: "Sport exhaust fitted at factory. 30mm lower. The most driver-focused Panamera for those who want it all.",
        price: "$152,250",
        specs: { power: "473 hp", acceleration: "3.7 s", topSpeed: "187 mph", engine: "4.0L V8 Biturbo" },
        badge: "GTS",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-025.jpg",
        link: "model-details.html?model=panamera-gts"
    },
    {
        id: "panamera-turbo-s",
        family: "Panamera",
        name: "Panamera Turbo S",
        tagline: "The flagship grand tourer.",
        description: "630 hp. 3.1 seconds. A 4-door producing supercar performance while remaining the most comfortable Panamera ever.",
        price: "$213,200",
        specs: { power: "630 hp", acceleration: "3.1 s", topSpeed: "196 mph", engine: "4.0L V8 Biturbo" },
        badge: "Turbo S",
        badgeClass: "badge-sport",
        image: "assets/images/top_view/ezgif-frame-033.jpg",
        link: "model-details.html?model=panamera-turbo-s"
    },
    {
        id: "panamera-4-e-hybrid",
        family: "Panamera",
        name: "Panamera 4 E-Hybrid",
        tagline: "Electrified grand touring.",
        description: "A 2.9L V6 plus an electric motor — 462 hp total system output with up to 31 miles of pure electric range.",
        price: "$115,200",
        specs: { power: "462 hp", acceleration: "4.2 s", topSpeed: "174 mph", engine: "Hybrid V6 + EV" },
        badge: "Hybrid",
        badgeClass: "badge-electric",
        image: "assets/images/top_view/ezgif-frame-018.jpg",
        link: "model-details.html?model=panamera-4-e-hybrid"
    },

    // ─────────────── MACAN FAMILY ───────────────────────────
    {
        id: "macan",
        family: "Macan",
        name: "Macan",
        tagline: "Compact SUV. Porsche soul.",
        description: "The all-electric Macan. The first Porsche built natively on the Premium Platform Electric — intense life awaits.",
        price: "$60,900",
        specs: { power: "295 hp", acceleration: "6.2 s", topSpeed: "137 mph", engine: "Single Motor EV RWD" },
        badge: "Electric",
        badgeClass: "badge-electric",
        image: "assets/images/side_view/ezgif-frame-008.jpg",
        link: "model-details.html?model=macan"
    },
    {
        id: "macan-4",
        family: "Macan",
        name: "Macan 4",
        tagline: "AWD precision. Every road.",
        description: "All-wheel drive electric with 408 hp and a 0-60 in 5.2 seconds. The compact SUV that corners like a sports car.",
        price: "$69,100",
        specs: { power: "408 hp", acceleration: "5.2 s", topSpeed: "137 mph", engine: "Dual Motor EV AWD" },
        badge: "AWD",
        badgeClass: "badge-new",
        image: "assets/images/side_view/ezgif-frame-018.jpg",
        link: "model-details.html?model=macan-4"
    },
    {
        id: "macan-turbo",
        family: "Macan",
        name: "Macan Turbo",
        tagline: "Performance SUV. No apology.",
        description: "630 hp all-wheel drive, 0-60 in 3.3 seconds, and an SUV body that forgets it's an SUV the moment you push the throttle.",
        price: "$99,900",
        specs: { power: "630 hp", acceleration: "3.3 s", topSpeed: "155 mph", engine: "Dual Motor EV AWD" },
        badge: "Turbo",
        badgeClass: "badge-sport",
        image: "assets/images/side_view/ezgif-frame-035.jpg",
        link: "model-details.html?model=macan-turbo"
    },

    // ─────────────── CAYENNE FAMILY ─────────────────────────
    {
        id: "cayenne",
        family: "Cayenne",
        name: "Cayenne",
        tagline: "The sports family SUV.",
        description: "The SUV that proved you don't have to sacrifice performance for practicality. A Porsche, first and always.",
        price: "$79,200",
        specs: { power: "348 hp", acceleration: "5.7 s", topSpeed: "154 mph", engine: "3.0L V6 Turbo" },
        badge: "SUV",
        badgeClass: "badge-suv",
        image: "assets/images/bottom_view/ezgif-frame-016.jpg",
        link: "model-details.html?model=cayenne"
    },
    {
        id: "cayenne-s",
        family: "Cayenne",
        name: "Cayenne S",
        tagline: "More power. More style.",
        description: "A 2.9L twin-turbo V6 producing 468 hp in a body that turns heads just as effectively as it turns corners.",
        price: "$100,150",
        specs: { power: "468 hp", acceleration: "4.5 s", topSpeed: "164 mph", engine: "2.9L V6 Biturbo" },
        badge: "S",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-025.jpg",
        link: "model-details.html?model=cayenne-s"
    },
    {
        id: "cayenne-gts",
        family: "Cayenne",
        name: "Cayenne GTS",
        tagline: "SUV. Sports car. Legend.",
        description: "Sport exhaust standard, lower suspension, and a 4.0L V8. The Cayenne that sounds as spectacular as it performs.",
        price: "$130,050",
        specs: { power: "468 hp", acceleration: "4.5 s", topSpeed: "164 mph", engine: "4.0L V8 Biturbo" },
        badge: "GTS",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-035.jpg",
        link: "model-details.html?model=cayenne-gts"
    },
    {
        id: "cayenne-turbo",
        family: "Cayenne",
        name: "Cayenne Turbo E-Hybrid",
        tagline: "V8 meets electric might.",
        description: "729 hp total system output from a V8 turbo and electric motor. The world's most powerful production Cayenne.",
        price: "$163,000",
        specs: { power: "729 hp", acceleration: "3.7 s", topSpeed: "183 mph", engine: "4.0L V8 + EV Hybrid" },
        badge: "Turbo",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-048.jpg",
        link: "model-details.html?model=cayenne-turbo"
    },
    {
        id: "cayenne-turbo-gt",
        family: "Cayenne",
        name: "Cayenne Turbo GT",
        tagline: "The Nürburgring SUV lap record holder.",
        description: "670 hp. A carbon fibre roof. Completely unique suspension tuning. An SUV that holds the Nürburgring record for its class.",
        price: "$186,700",
        specs: { power: "670 hp", acceleration: "3.3 s", topSpeed: "186 mph", engine: "4.0L V8 Biturbo" },
        badge: "GT",
        badgeClass: "badge-new",
        image: "assets/images/bottom_view/ezgif-frame-060.jpg",
        link: "model-details.html?model=cayenne-turbo-gt"
    },
    {
        id: "cayenne-coupe",
        family: "Cayenne",
        name: "Cayenne Coupé",
        tagline: "SUV athleticism. Coupe beauty.",
        description: "A roofline that flows like a sports car, an adaptive rear spoiler, and the same Cayenne DNA but more visually dramatic.",
        price: "$83,700",
        specs: { power: "348 hp", acceleration: "5.9 s", topSpeed: "152 mph", engine: "3.0L V6 Turbo" },
        badge: "Coupé",
        badgeClass: "badge-icon",
        image: "assets/images/bottom_view/ezgif-frame-020.jpg",
        link: "model-details.html?model=cayenne-coupe"
    },
    {
        id: "cayenne-e-hybrid",
        family: "Cayenne",
        name: "Cayenne E-Hybrid",
        tagline: "Plug-in power. Every day.",
        description: "Up to 42 miles of electric range meets 470 hp when the V6 kicks in — seamlessly, silently, superbly.",
        price: "$90,900",
        specs: { power: "470 hp", acceleration: "4.7 s", topSpeed: "157 mph", engine: "V6 + EV Hybrid" },
        badge: "Hybrid",
        badgeClass: "badge-electric",
        image: "assets/images/bottom_view/ezgif-frame-010.jpg",
        link: "model-details.html?model=cayenne-e-hybrid"
    },

    // ─────────────── 718 FAMILY ─────────────────────────────
    {
        id: "718-boxster",
        family: "718",
        name: "718 Boxster",
        tagline: "Mid-engine. Open top. Pure.",
        description: "A flat-four turbo, a mid-engine layout, and a retractable fabric roof — the distilled essence of open-air sports driving.",
        price: "$68,300",
        specs: { power: "300 hp", acceleration: "4.9 s", topSpeed: "170 mph", engine: "2.0L Flat-4 Turbo" },
        badge: "Roadster",
        badgeClass: "badge-icon",
        image: "assets/images/bottom_view/ezgif-frame-005.jpg",
        link: "model-details.html?model=718-boxster"
    },
    {
        id: "718-boxster-s",
        family: "718",
        name: "718 Boxster S",
        tagline: "More cylinders. More soul.",
        description: "350 hp from a 2.5L flat-four, a Sport Chrono Package and a chassis tuned for those who demand more from every corner.",
        price: "$80,700",
        specs: { power: "350 hp", acceleration: "4.4 s", topSpeed: "177 mph", engine: "2.5L Flat-4 Turbo" },
        badge: "S",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-012.jpg",
        link: "model-details.html?model=718-boxster-s"
    },
    {
        id: "718-boxster-gts",
        family: "718",
        name: "718 Boxster GTS 4.0",
        tagline: "Naturally aspirated perfection.",
        description: "400 hp. A 4.0L naturally aspirated flat-six. Rev to 7,800 rpm and hear a sound that no turbocharged car can replicate.",
        price: "$101,900",
        specs: { power: "400 hp", acceleration: "4.0 s", topSpeed: "181 mph", engine: "4.0L Flat-6 NA" },
        badge: "GTS",
        badgeClass: "badge-new",
        image: "assets/images/bottom_view/ezgif-frame-040.jpg",
        link: "model-details.html?model=718-boxster-gts"
    },
    {
        id: "718-cayman",
        family: "718",
        name: "718 Cayman",
        tagline: "Hardtop. Mid-engine. Perfect.",
        description: "The coupe that defines mid-engine balance. A stiffer body, a purer chassis and the same iconic Porsche formula.",
        price: "$68,300",
        specs: { power: "300 hp", acceleration: "4.7 s", topSpeed: "170 mph", engine: "2.0L Flat-4 Turbo" },
        badge: "Coupe",
        badgeClass: "badge-icon",
        image: "assets/images/bottom_view/ezgif-frame-018.jpg",
        link: "model-details.html?model=718-cayman"
    },
    {
        id: "718-cayman-s",
        family: "718",
        name: "718 Cayman S",
        tagline: "The coupe for purists.",
        description: "350 hp, Sport Chrono standard, and the stiffest body in the 718 range. The recipe for driving perfection.",
        price: "$80,700",
        specs: { power: "350 hp", acceleration: "4.2 s", topSpeed: "177 mph", engine: "2.5L Flat-4 Turbo" },
        badge: "S",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-028.jpg",
        link: "model-details.html?model=718-cayman-s"
    },
    {
        id: "718-cayman-gt4-rs",
        family: "718",
        name: "718 Cayman GT4 RS",
        tagline: "Track weapon. Road legal.",
        description: "500 hp, a 9,000 rpm flat-six and aerodynamics derived directly from the 911 GT3 RS — the sharpest 718 ever made.",
        price: "$142,700",
        specs: { power: "500 hp", acceleration: "3.4 s", topSpeed: "196 mph", engine: "4.0L Flat-6 NA" },
        badge: "GT4 RS",
        badgeClass: "badge-sport",
        image: "assets/images/bottom_view/ezgif-frame-056.jpg",
        link: "model-details.html?model=718-cayman-gt4-rs"
    },
];

// Family metadata for UI grouping
const modelFamilies = [
    { id: "all", label: "All Models", icon: "◈" },
    { id: "911", label: "911", icon: "●" },
    { id: "Taycan", label: "Taycan", icon: "⚡" },
    { id: "Panamera", label: "Panamera", icon: "◆" },
    { id: "Macan", label: "Macan", icon: "▲" },
    { id: "Cayenne", label: "Cayenne", icon: "■" },
    { id: "718", label: "718", icon: "▷" },
];
